trigger:
- main

pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : INIT'
  inputs:
    backendServiceArm: 'poc-infra-TFSPN'
    backendAzureRmResourceGroupName: 'poc-infra'
    backendAzureRmStorageAccountName: nmgpocinfra
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: 'jOcGaiJLwtgk9uu7rjg3Mb6qILslrdqxs/+K4PkyJCN5d/FOha4TOAKB62M5gqZuDKNz1fIaL5RWGzdpqNMenw=='

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : PLAN'
  inputs:
    command: plan
    environmentServiceNameAzureRM: 'poc-infra-TFSPN'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : VAL & APPLY'
  inputs:
    command: apply
    environmentServiceNameAzureRM: 'poc-infra-TFSPN'
